FROM centos:centos7
# Capa de instalacion
RUN \
    yum -y install \ 
    httpd \ 
    php \ 
    php-cli \ 
    php-common \
    mod_ssl \
    openssl

# Capa de configuracion
RUN echo "<?php phpinfo(); ?>" > /var/www/html/hola.php
# Capa de copiado de archivos
COPY  startbootstrap-sb-admin-2 /var/www/html
# Configuracion de certificado ssl
COPY docker.crt /docker.crt
COPY docker.key /docker.key
COPY ssl.conf /etc/httpd/conf.d/default.conf

EXPOSE 443
CMD apachectl -DFOREGROUND