version: '3'

services:
  reaction:
    image: reactioncommerce/reaction
    networks:
      - net
    depends_on:
      - mongo
    ports:
      - "3000:3000"
    environment:
      ROOT_URL: "http://localhost"
      MONGO_URL: "mongodb://mongo:27017/reaction"
      STORE_URL: ""
  mongo:
    image: mongo
    volumes:
      - mongo-volume:/data/db
    networks:
      - net

networks:
  net:
volumes:
  mongo-volume: